import useFinModelStore, {
  resolveFinModelStreamKey,
  type FinModelStreamKey,
} from "@/store/useFinModelStore";
import {
  resolveComponent4EquityHeadlines,
  resolveLeveredEquityIrrPctFromFinModelStore,
  resolveUnleveredProjectIrrPct,
} from "@/lib/scenario-irr-calculation";

export type FeasibilityProjectInfo = {
  location: string;
  assetType: string;
  segment: string;
  totalBUA: number;
  constructionPeriod: string;
  currency: string;
};

export type FeasibilityFinancials = {
  tdc: number;
  gdv: number;
  projectIRR: number;
  equityIRR: number;
  equityMultiple: number;
  paybackPeriod: number;
  netProfitMargin: number;
};

export type FeasibilityMarketAnalysis = {
  macroOverview: string;
  realEstateMarket: string;
  implications: string;
};

export type FeasibilityReportData = {
  projectInfo: FeasibilityProjectInfo;
  financials: FeasibilityFinancials;
  marketAnalysis: FeasibilityMarketAnalysis;
};

function formatAssetType(buildingType: string | undefined): string {
  if (!buildingType) return "Development";
  return buildingType.charAt(0).toUpperCase() + buildingType.slice(1);
}

function totalBuaFromCashOutflows(cashOutflows: {
  buildingBUA: number;
  parkingBUA: number;
  basementBUA: number;
}): number {
  return (
    (cashOutflows.buildingBUA || 0) +
    (cashOutflows.parkingBUA || 0) +
    (cashOutflows.basementBUA || 0)
  );
}

function paybackYears(
  financingPaybackMonth: number | undefined,
  equityPaybackMonths: number | null | undefined
): number {
  const months =
    financingPaybackMonth ??
    (equityPaybackMonths != null && equityPaybackMonths > 0
      ? equityPaybackMonths
      : null);
  if (months == null || !Number.isFinite(months)) return 0;
  return Math.round((months / 12) * 10) / 10;
}

export function generateReportData(
  stream?: FinModelStreamKey
): FeasibilityReportData {
  const state = useFinModelStore.getState();
  const streamKey = resolveFinModelStreamKey(stream, state.assetType);
  const slice = state[streamKey];
  const rootProjectIRR =
    streamKey === "operational" ? state.projectIRR : undefined;

  const { projectInfo, cashOutflows, cashInflows, projectIRR, financingMetrics } =
    slice;

  const component4 = resolveComponent4EquityHeadlines({
    financingMetrics,
    projectIRR,
  });

  const projectIRRPercent =
    resolveUnleveredProjectIrrPct(projectIRR, rootProjectIRR) ?? 0;

  const equityIRRPercent =
    resolveLeveredEquityIrrPctFromFinModelStore({
      financingMetrics,
      projectIRR,
    }) ??
    component4.leveredIrrPct ??
    0;

  const tdc = cashOutflows.tdc || 0;
  const gdv =
    cashInflows.grossSales ||
    financingMetrics?.netExitProceeds ||
    (tdc > 0 ? tdc * 1.2 : 0);

  const netProfitMargin =
    gdv > 0 ? Math.round(((gdv - tdc) / gdv) * 1000) / 10 : 0;

  const city = projectInfo.city?.trim() || "—";
  const country = projectInfo.country?.trim() || "—";

  const segment =
    projectInfo.businessModel ||
    projectInfo.buildingSubType ||
    projectInfo.stream ||
    streamKey;

  return {
    projectInfo: {
      location: `${city}, ${country}`,
      assetType: formatAssetType(projectInfo.buildingType),
      segment: String(segment),
      totalBUA: totalBuaFromCashOutflows(cashOutflows),
      constructionPeriod: `${cashOutflows.constructionPeriod || 0} months`,
      currency: projectInfo.currency || "AED",
    },
    financials: {
      tdc,
      gdv,
      projectIRR: Math.round(projectIRRPercent * 100) / 100,
      equityIRR: Math.round(equityIRRPercent * 100) / 100,
      equityMultiple:
        Math.round((component4.equityMultiple || 0) * 100) / 100,
      paybackPeriod: paybackYears(
        financingMetrics?.equityPayback,
        slice.equityReturns.paybackPeriod
      ),
      netProfitMargin,
    },
    marketAnalysis: {
      macroOverview: `Macroeconomic overview for ${country} will be generated by AI in Phase 2.`,
      realEstateMarket: `Real estate market analysis for ${city} will be generated by AI in Phase 2.`,
      implications: `Implications for the ${formatAssetType(projectInfo.buildingType)} project will be generated by AI in Phase 2.`,
    },
  };
}
