import type { HotelOperatingType } from "@/config/hotel-cost-profiles";
import { inferHotelProfileRegion } from "@/config/hotel-cost-profiles";

export type DirectCostProfile = {
  roomsPayroll: number;
  roomsOther: number;
  foodCostOfSale: number;
  beverageCostOfSale: number;
  fbPayroll: number;
  fbOther: number;
  telecomCost: number;
  healthLeisureCost: number;
  otherDeptsCost: number;
  source: string;
  regions: string[];
};

export const HOTEL_DIRECT_COST_PROFILES: Record<string, DirectCostProfile> = {
  "business-5-dubai": {
    roomsPayroll: 8.0,
    roomsOther: 7.0,
    foodCostOfSale: 31.0,
    beverageCostOfSale: 20.0,
    fbPayroll: 23.0,
    fbOther: 10.0,
    telecomCost: 43.0,
    healthLeisureCost: 55.0,
    otherDeptsCost: 22.0,
    source: "HVS Dubai Hotel Operations Benchmarking 2024",
    regions: ["dubai", "uae", "gcc"],
  },
  "business-4-dubai": {
    roomsPayroll: 9.0,
    roomsOther: 7.5,
    foodCostOfSale: 32.0,
    beverageCostOfSale: 21.0,
    fbPayroll: 24.0,
    fbOther: 10.5,
    telecomCost: 44.0,
    healthLeisureCost: 56.0,
    otherDeptsCost: 23.0,
    source: "JLL Middle East Hotel Operations Report 2024",
    regions: ["dubai", "uae", "gcc"],
  },
  "business-3-dubai": {
    roomsPayroll: 10.0,
    roomsOther: 8.0,
    foodCostOfSale: 33.0,
    beverageCostOfSale: 22.0,
    fbPayroll: 25.0,
    fbOther: 11.0,
    telecomCost: 45.0,
    healthLeisureCost: 57.0,
    otherDeptsCost: 24.0,
    source: "STR GCC Midscale Hotel Benchmarks",
    regions: ["dubai", "uae", "gcc"],
  },
  "resort-5-dubai": {
    roomsPayroll: 7.0,
    roomsOther: 6.0,
    foodCostOfSale: 29.0,
    beverageCostOfSale: 18.0,
    fbPayroll: 26.0,
    fbOther: 11.0,
    telecomCost: 40.0,
    healthLeisureCost: 60.0,
    otherDeptsCost: 20.0,
    source: "HVS Resort Operations Survey — GCC",
    regions: ["dubai", "uae", "gcc"],
  },
  "resort-4-dubai": {
    roomsPayroll: 7.5,
    roomsOther: 6.5,
    foodCostOfSale: 30.0,
    beverageCostOfSale: 19.0,
    fbPayroll: 25.0,
    fbOther: 10.5,
    telecomCost: 41.0,
    healthLeisureCost: 58.0,
    otherDeptsCost: 21.0,
    source: "JLL Middle East Leisure Hospitality Report",
    regions: ["dubai", "uae", "gcc"],
  },
  "boutique-4-dubai": {
    roomsPayroll: 8.5,
    roomsOther: 7.0,
    foodCostOfSale: 30.0,
    beverageCostOfSale: 19.0,
    fbPayroll: 24.0,
    fbOther: 10.0,
    telecomCost: 42.0,
    healthLeisureCost: 54.0,
    otherDeptsCost: 22.0,
    source: "CBRE Boutique Hotel Trends — MENA",
    regions: ["dubai", "uae", "gcc"],
  },
  "boutique-3-dubai": {
    roomsPayroll: 9.5,
    roomsOther: 8.0,
    foodCostOfSale: 32.0,
    beverageCostOfSale: 21.0,
    fbPayroll: 25.0,
    fbOther: 11.0,
    telecomCost: 44.0,
    healthLeisureCost: 56.0,
    otherDeptsCost: 23.0,
    source: "STR Boutique Segment — GCC",
    regions: ["dubai", "uae", "gcc"],
  },
  "budget-1-dubai": {
    roomsPayroll: 12.0,
    roomsOther: 9.0,
    foodCostOfSale: 35.0,
    beverageCostOfSale: 25.0,
    fbPayroll: 28.0,
    fbOther: 12.0,
    telecomCost: 50.0,
    healthLeisureCost: 0,
    otherDeptsCost: 25.0,
    source: "HVS Economy Hotel Benchmarks — MENA",
    regions: ["dubai", "uae", "gcc"],
  },

  "business-5-malaysia": {
    roomsPayroll: 8.5,
    roomsOther: 7.0,
    foodCostOfSale: 30.0,
    beverageCostOfSale: 19.0,
    fbPayroll: 22.0,
    fbOther: 9.5,
    telecomCost: 42.0,
    healthLeisureCost: 54.0,
    otherDeptsCost: 21.0,
    source: "JLL Malaysia Hotel Operations Report 2024",
    regions: ["malaysia", "kl", "penang"],
  },
  "business-4-malaysia": {
    roomsPayroll: 9.0,
    roomsOther: 7.5,
    foodCostOfSale: 31.0,
    beverageCostOfSale: 20.0,
    fbPayroll: 23.0,
    fbOther: 10.0,
    telecomCost: 43.0,
    healthLeisureCost: 55.0,
    otherDeptsCost: 22.0,
    source: "CBRE Malaysia Hospitality Report 2024",
    regions: ["malaysia", "kl", "penang"],
  },
  "business-3-malaysia": {
    roomsPayroll: 10.0,
    roomsOther: 8.0,
    foodCostOfSale: 32.0,
    beverageCostOfSale: 21.0,
    fbPayroll: 24.0,
    fbOther: 10.5,
    telecomCost: 44.0,
    healthLeisureCost: 56.0,
    otherDeptsCost: 23.0,
    source: "STR Malaysia Midscale Benchmarks",
    regions: ["malaysia", "kl", "penang"],
  },
  "resort-5-malaysia": {
    roomsPayroll: 7.0,
    roomsOther: 6.0,
    foodCostOfSale: 28.0,
    beverageCostOfSale: 17.0,
    fbPayroll: 25.0,
    fbOther: 10.5,
    telecomCost: 39.0,
    healthLeisureCost: 59.0,
    otherDeptsCost: 19.0,
    source: "HVS Asia Pacific Resort Survey",
    regions: ["malaysia", "langkawi", "kotakinabalu"],
  },
  "resort-4-malaysia": {
    roomsPayroll: 7.5,
    roomsOther: 6.5,
    foodCostOfSale: 29.0,
    beverageCostOfSale: 18.0,
    fbPayroll: 24.0,
    fbOther: 10.0,
    telecomCost: 40.0,
    healthLeisureCost: 57.0,
    otherDeptsCost: 20.0,
    source: "JLL Malaysia Leisure Report",
    regions: ["malaysia", "langkawi", "kotakinabalu"],
  },
  "boutique-4-malaysia": {
    roomsPayroll: 8.5,
    roomsOther: 7.0,
    foodCostOfSale: 29.5,
    beverageCostOfSale: 18.5,
    fbPayroll: 23.0,
    fbOther: 9.5,
    telecomCost: 41.0,
    healthLeisureCost: 53.0,
    otherDeptsCost: 21.0,
    source: "CBRE Boutique Trends — SEA",
    regions: ["malaysia", "kl", "penang"],
  },
  "boutique-3-malaysia": {
    roomsPayroll: 9.5,
    roomsOther: 8.0,
    foodCostOfSale: 31.0,
    beverageCostOfSale: 20.0,
    fbPayroll: 24.0,
    fbOther: 10.5,
    telecomCost: 43.0,
    healthLeisureCost: 55.0,
    otherDeptsCost: 22.0,
    source: "STR Boutique — Malaysia",
    regions: ["malaysia", "kl", "penang"],
  },
  "budget-1-malaysia": {
    roomsPayroll: 12.5,
    roomsOther: 9.5,
    foodCostOfSale: 34.0,
    beverageCostOfSale: 24.0,
    fbPayroll: 27.0,
    fbOther: 11.5,
    telecomCost: 49.0,
    healthLeisureCost: 0,
    otherDeptsCost: 24.0,
    source: "HVS Economy Benchmarks — SEA",
    regions: ["malaysia", "kl", "jb"],
  },

  "business-5-australia": {
    roomsPayroll: 7.5,
    roomsOther: 6.5,
    foodCostOfSale: 29.0,
    beverageCostOfSale: 18.0,
    fbPayroll: 21.0,
    fbOther: 9.0,
    telecomCost: 41.0,
    healthLeisureCost: 52.0,
    otherDeptsCost: 20.0,
    source: "HVS Australia Hotel Benchmarking 2024",
    regions: ["australia", "sydney", "melbourne"],
  },
  "business-4-australia": {
    roomsPayroll: 8.0,
    roomsOther: 7.0,
    foodCostOfSale: 30.0,
    beverageCostOfSale: 19.0,
    fbPayroll: 22.0,
    fbOther: 9.5,
    telecomCost: 42.0,
    healthLeisureCost: 53.0,
    otherDeptsCost: 21.0,
    source: "JLL Australia Hospitality Report 2024",
    regions: ["australia", "sydney", "melbourne"],
  },
  "business-3-australia": {
    roomsPayroll: 9.0,
    roomsOther: 7.5,
    foodCostOfSale: 31.0,
    beverageCostOfSale: 20.0,
    fbPayroll: 23.0,
    fbOther: 10.0,
    telecomCost: 43.0,
    healthLeisureCost: 54.0,
    otherDeptsCost: 22.0,
    source: "STR Australia Midscale Benchmarks",
    regions: ["australia", "brisbane", "perth"],
  },
  "resort-5-australia": {
    roomsPayroll: 6.5,
    roomsOther: 5.5,
    foodCostOfSale: 27.0,
    beverageCostOfSale: 16.0,
    fbPayroll: 24.0,
    fbOther: 10.0,
    telecomCost: 38.0,
    healthLeisureCost: 58.0,
    otherDeptsCost: 18.0,
    source: "HVS Resort Survey — APAC",
    regions: ["australia", "goldcoast", "cairns"],
  },
  "resort-4-australia": {
    roomsPayroll: 7.0,
    roomsOther: 6.0,
    foodCostOfSale: 28.0,
    beverageCostOfSale: 17.0,
    fbPayroll: 23.0,
    fbOther: 9.5,
    telecomCost: 39.0,
    healthLeisureCost: 56.0,
    otherDeptsCost: 19.0,
    source: "JLL Australia Leisure Report",
    regions: ["australia", "goldcoast", "cairns"],
  },
  "boutique-4-australia": {
    roomsPayroll: 8.0,
    roomsOther: 6.5,
    foodCostOfSale: 28.5,
    beverageCostOfSale: 17.5,
    fbPayroll: 22.0,
    fbOther: 9.0,
    telecomCost: 40.0,
    healthLeisureCost: 51.0,
    otherDeptsCost: 20.0,
    source: "CBRE Boutique Trends — Australia",
    regions: ["australia", "sydney", "melbourne"],
  },
  "boutique-3-australia": {
    roomsPayroll: 9.0,
    roomsOther: 7.5,
    foodCostOfSale: 30.0,
    beverageCostOfSale: 19.0,
    fbPayroll: 23.0,
    fbOther: 10.0,
    telecomCost: 42.0,
    healthLeisureCost: 53.0,
    otherDeptsCost: 21.0,
    source: "STR Boutique — Australia",
    regions: ["australia", "sydney", "melbourne"],
  },
  "budget-1-australia": {
    roomsPayroll: 11.5,
    roomsOther: 8.5,
    foodCostOfSale: 33.0,
    beverageCostOfSale: 23.0,
    fbPayroll: 26.0,
    fbOther: 11.0,
    telecomCost: 48.0,
    healthLeisureCost: 0,
    otherDeptsCost: 23.0,
    source: "HVS Economy Benchmarks — ANZ",
    regions: ["australia", "sydney", "melbourne"],
  },

  "business-5-china": {
    roomsPayroll: 7.0,
    roomsOther: 6.0,
    foodCostOfSale: 28.0,
    beverageCostOfSale: 17.0,
    fbPayroll: 20.0,
    fbOther: 9.0,
    telecomCost: 40.0,
    healthLeisureCost: 50.0,
    otherDeptsCost: 19.0,
    source: "HVS China Hotel Operations Benchmarking 2024",
    regions: ["china", "shanghai", "beijing", "hk"],
  },
  "business-4-china": {
    roomsPayroll: 7.5,
    roomsOther: 6.5,
    foodCostOfSale: 29.0,
    beverageCostOfSale: 18.0,
    fbPayroll: 21.0,
    fbOther: 9.5,
    telecomCost: 41.0,
    healthLeisureCost: 51.0,
    otherDeptsCost: 20.0,
    source: "JLL China Hospitality Report 2024",
    regions: ["china", "shanghai", "beijing", "hk"],
  },
  "business-3-china": {
    roomsPayroll: 8.5,
    roomsOther: 7.0,
    foodCostOfSale: 30.0,
    beverageCostOfSale: 19.0,
    fbPayroll: 22.0,
    fbOther: 10.0,
    telecomCost: 42.0,
    healthLeisureCost: 52.0,
    otherDeptsCost: 21.0,
    source: "STR China Midscale Benchmarks",
    regions: ["china", "guangzhou", "shenzhen"],
  },
  "resort-5-china": {
    roomsPayroll: 6.0,
    roomsOther: 5.0,
    foodCostOfSale: 26.0,
    beverageCostOfSale: 15.0,
    fbPayroll: 23.0,
    fbOther: 9.5,
    telecomCost: 37.0,
    healthLeisureCost: 57.0,
    otherDeptsCost: 17.0,
    source: "HVS Resort Survey — Greater China",
    regions: ["china", "sanya", "hangzhou", "hk"],
  },
  "resort-4-china": {
    roomsPayroll: 6.5,
    roomsOther: 5.5,
    foodCostOfSale: 27.0,
    beverageCostOfSale: 16.0,
    fbPayroll: 22.0,
    fbOther: 9.0,
    telecomCost: 38.0,
    healthLeisureCost: 55.0,
    otherDeptsCost: 18.0,
    source: "JLL China Leisure Report",
    regions: ["china", "sanya", "hangzhou", "hk"],
  },
  "boutique-4-china": {
    roomsPayroll: 7.5,
    roomsOther: 6.0,
    foodCostOfSale: 27.5,
    beverageCostOfSale: 16.5,
    fbPayroll: 21.0,
    fbOther: 8.5,
    telecomCost: 39.0,
    healthLeisureCost: 49.0,
    otherDeptsCost: 19.0,
    source: "CBRE Boutique Trends — Greater China",
    regions: ["china", "shanghai", "beijing", "hk"],
  },
  "boutique-3-china": {
    roomsPayroll: 8.5,
    roomsOther: 7.0,
    foodCostOfSale: 29.0,
    beverageCostOfSale: 18.0,
    fbPayroll: 22.0,
    fbOther: 9.5,
    telecomCost: 41.0,
    healthLeisureCost: 51.0,
    otherDeptsCost: 20.0,
    source: "STR Boutique — China",
    regions: ["china", "shanghai", "beijing", "hk"],
  },
  "budget-1-china": {
    roomsPayroll: 11.0,
    roomsOther: 8.0,
    foodCostOfSale: 32.0,
    beverageCostOfSale: 22.0,
    fbPayroll: 25.0,
    fbOther: 10.5,
    telecomCost: 47.0,
    healthLeisureCost: 0,
    otherDeptsCost: 22.0,
    source: "HVS Economy Benchmarks — China",
    regions: ["china", "tier2", "tier3"],
  },

  default: {
    roomsPayroll: 8.0,
    roomsOther: 7.0,
    foodCostOfSale: 31.0,
    beverageCostOfSale: 20.0,
    fbPayroll: 23.0,
    fbOther: 10.0,
    telecomCost: 43.0,
    healthLeisureCost: 55.0,
    otherDeptsCost: 22.0,
    source: "Industry baseline — please validate with local data",
    regions: ["global"],
  },
};

export type HotelDirectCostPctKey = keyof Omit<
  DirectCostProfile,
  "source" | "regions"
>;

export const HOTEL_DIRECT_COST_PCT_KEYS: HotelDirectCostPctKey[] = [
  "roomsPayroll",
  "roomsOther",
  "foodCostOfSale",
  "beverageCostOfSale",
  "fbPayroll",
  "fbOther",
  "telecomCost",
  "healthLeisureCost",
  "otherDeptsCost",
];

export const DIRECT_COST_STACK_KEYS = [
  "dcRoomsPayroll",
  "dcRoomsOther",
  "dcFoodCos",
  "dcBeverageCos",
  "dcFbPayroll",
  "dcFbOther",
  "dcTelecom",
  "dcHealthLeisure",
  "dcOtherDepts",
] as const;

export type DirectCostStackKey = (typeof DIRECT_COST_STACK_KEYS)[number];

export const DIRECT_COST_STACK_LABELS: Record<DirectCostStackKey, string> = {
  dcRoomsPayroll: "Rooms — payroll",
  dcRoomsOther: "Rooms — other",
  dcFoodCos: "Food — cost of sales",
  dcBeverageCos: "Beverage — cost of sales",
  dcFbPayroll: "F&B — payroll",
  dcFbOther: "F&B — other",
  dcTelecom: "Telecom",
  dcHealthLeisure: "Spa & health",
  dcOtherDepts: "Rental & other depts.",
};

export const DIRECT_COST_STACK_COLORS: Record<DirectCostStackKey, string> = {
  dcRoomsPayroll: "#059669",
  dcRoomsOther: "#10b981",
  dcFoodCos: "#d97706",
  dcBeverageCos: "#ea580c",
  dcFbPayroll: "#f59e0b",
  dcFbOther: "#fbbf24",
  dcTelecom: "#64748b",
  dcHealthLeisure: "#9333ea",
  dcOtherDepts: "#0891b2",
};

export function pctsFromDirectCostProfile(
  p: DirectCostProfile
): Record<HotelDirectCostPctKey, number> {
  return {
    roomsPayroll: p.roomsPayroll,
    roomsOther: p.roomsOther,
    foodCostOfSale: p.foodCostOfSale,
    beverageCostOfSale: p.beverageCostOfSale,
    fbPayroll: p.fbPayroll,
    fbOther: p.fbOther,
    telecomCost: p.telecomCost,
    healthLeisureCost: p.healthLeisureCost,
    otherDeptsCost: p.otherDeptsCost,
  };
}

export function resolveHotelDirectCostProfile(
  hotelType: HotelOperatingType,
  starRating: number,
  country: string,
  city: string
): { key: string; profile: DirectCostProfile } {
  const region = inferHotelProfileRegion(country, city);
  const key = `${hotelType}-${starRating}-${region}`;
  const profile = HOTEL_DIRECT_COST_PROFILES[key];
  if (profile) return { key, profile };
  return { key: "default", profile: HOTEL_DIRECT_COST_PROFILES.default };
}

export function getDirectCostProfileKey(
  hotelType: HotelOperatingType,
  starRating: number,
  region: "dubai" | "malaysia" | "australia" | "china" = "dubai"
): string {
  const key = `${hotelType}-${starRating}-${region}`;
  return HOTEL_DIRECT_COST_PROFILES[key] ? key : "default";
}
